### ISSUE TITLE
included Jetty (in testbench core) will lead to exception on V10 if you are not using Jetty 

### ISSUE THREAD

**Issue by svenruppert** [vaadin/testbench#1105]
Please, 
remove the included Selenium-server from the jar.
If you are using testbench with something other as Jetty, Push will not work
with V10. You have to exclude the transitive Jetty.

The error with Tomcat based Containern is for example:

> Failed to initialize Atmosphere Framework
java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/servlet/WebSocketCreator
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
	at java.base/java.lang.Class.getConstructor0(Class.java:3295)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2512)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:236)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2085)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.flow.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:218)
	at com.vaadin.flow.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:89)
	at com.vaadin.flow.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:82)
	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:243)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:259)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:240)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:77)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1124)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1079)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.servlet.WebSocketCreator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 36 more

With the exclude it will work...

```xml
<dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-testbench-core</artifactId>
        <version>${vaadin-testbench-v10.version}</version>
        <exclusions>
          <exclusion>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
          </exclusion>
        </exclusions>
        <!--<scope>test</scope>-->
      </dependency>
```

**Comment by Artur-** [comment]
Why do you have `<scope>test</scope>` commented out? There should never be any need to have testbench deployed

**Comment by svenruppert** [comment]
I am working on something as add on..  this is why I have it in compile scope..  but the same is, if you are using it in a test with an other container.

**Comment by mstahv** [comment]
Why is selenium-server in the testbench-core anyways?

**Comment by alvarezguille** [comment]
>Why is selenium-server in the testbench-core anyways?

That's a good question, I don't think it's needed
