### ISSUE TITLE
Getting error: Selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.709

### ISSUE THREAD

**Issue by riteshsrivastav1991** [vaadin/testbench#1268]
When trying to launch URL by chromedriver , URL takes lot of time to open by driver however it opens manually faster. 
This is complete error:

C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\venv\Scripts\python.exe C:/Users/riteshs.IMTACHO/PycharmProjects/Empyreal_Universe/Test_Suits_Package/AllTestSuits.py
Traceback (most recent call last):
  File "C:/Users/riteshs.IMTACHO/PycharmProjects/Empyreal_Universe/Test_Suits_Package/AllTestSuits.py", line 2, in <module>
    from Basic_Authentication_Package.TC_LoginTest import LoginTest as lit
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\Basic_Authentication_Package\TC_LoginTest.py", line 3, in <module>
    from POM_Package.pg_login import loginpageLocators as lpl
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\POM_Package\pg_login.py", line 5, in <module>
    from config.appconfig import appconfig as ac
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\config\appconfig.py", line 4, in <module>
    class appconfig():
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\config\appconfig.py", line 22, in appconfig
    driver.get(url)
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\riteshs.IMTACHO\PycharmProjects\Empyreal_Universe\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.709
  (Session info: chrome=83.0.4103.116)

Process finished with exit code 1

Code snippet is as below:

from selenium import webdriver
from Test_Data.td_userSelection import userSelection

class appconfig():

    browserType = userSelection.var_browser
    url = userSelection.var_url
    #userSelection.launchURL(url, browserType)

    if browserType == "Chrome":
        # ..\Test_Data\TestSuitSelection.xlsx
        driver = webdriver.Chrome(executable_path='..\Browser_Drivers\chromedriver1.exe')

    if browserType == "Firefox":
        print("Firebox browser")
    if browserType == "Edge":
        print("Edge browser")
    if browserType == "Safari":
        print("Safari browser")

    driver.maximize_window()
    driver.get(url)
    driver.implicitly_wait(100)
    print("100 sec wait over")

    #driver.get("http://h2020.myspecies.info/")
    print("URL launched")
    #driver.quit()

**Comment by alvarezguille** [comment]
Hi @riteshsrivastav1991 I think this is a selenium issue and not a TestBench issue. In that case it can be reported in [selenium](http://github.com/seleniumhq/selenium/issues/new).
If you can reproduce this using Vaadin TestBench feel free to reopen.
