### ISSUE TITLE
TestBench doesn't wait for dev server to start

### ISSUE THREAD

**Issue by mshabarov** [vaadin/testbench#1303]
After upgrading TestBench version from `7.0.1` to `7.0.2` in Flow 8 the following IT tests have been failing abnormally
- RootContextIT::testScriptInjection
- TogglePushIT::togglePush
- ConnectionIndicatorIT::online_goingOffline_customisedMessageShown
- PwaTestIT::testPwaOfflinePath
- StreamResourceIT::detact_attachALink_getDynamicVaadinResource
(and other logically unrelated tests)

with a similar `NoSuchElementException` just after the first element is being discovered after page open. For instance:

```
java.lang.RuntimeException: testScriptInjection[ANY_Chrome_](com.vaadin.flow.contexttest.ui.RootContextIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:78)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#root"}
  (Session info: headless chrome=95.0.4638.54)
```

All the error screenshots show the same page with dev server loading indicator:
![image](https://user-images.githubusercontent.com/61410877/140745564-64f766be-de47-4610-984d-b21f2eecec8c.png)

Most likely, TestBench "wait for" logic is broken in `7.0.2`, probably because of this change https://github.com/vaadin/testbench/pull/1296

Flow 9 doesn't have such an issues even after upgrading to `7.0.2`, despite it has the same mechanism to check the dev server is being started:

`window.Vaadin = {Flow: {devServerIsNotLoaded: true}};`

and in the `TestBenchHelpers`:

```java
    protected void waitForDevServer() {
        Object result;
        do {
            getCommandExecutor().waitForVaadin();
            result = getCommandExecutor().executeScript(
                    "return window.Vaadin && window.Vaadin.Flow && window.Vaadin.Flow.devServerIsNotLoaded;");
        } while (Boolean.TRUE.equals(result));
    }
```

**Comment by ZheSun88** [comment]
fixed in #1304
