### ISSUE TITLE
Testbench sometimes fails to contact Opera 12

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#544]
**Originally by @Legioth**

___
Running a test with Opera 12 seems to randomly fail about 20% of the times. Tested with a remote test machine with Windows XP and Opera 12 through a remote hub.

This is the reported error message:
```
org.openqa.selenium.WebDriverException: No response on ECMAScript evaluation command
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Windows XP', os.arch: 'x86', os.version: '5.1', java.version: '1.6.0_15'
Driver info: driver.version: unknown
Command duration or timeout: 1.66 seconds
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-17-pve', java.version: '1.6.0_32'
Session ID: 34271ebf-875a-4d51-8edd-7faad246041b
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{platform=XP, opera.binary=C:\Program Files\Opera\opera.exe, opera.host=127.0.0.1, javascriptEnabled=true, browserName=opera, opera.idle=false, opera.detach=false, opera.autostart=true, opera.runner=com.opera.core.systems.runner.launcher.OperaLauncherRunner, opera.logging.level=INFO, webdriver.remote.sessionid=34271ebf-875a-4d51-8edd-7faad246041b, opera.profile={base64=UEsDBBQACAAIABlLDkMAAAAAAAAAAAAAAAAlAAAAYXBwbGljYXRpb25fY2FjaGVcbWNhY2hlXGFj
dGl2aXR5Lm9wcgMAUEsHCAAAAAACAAAAAAAAAFBLAwQUAAgACAAZSw5DAAAAAAAAAAAAAAAADQAA
...
dy5heHhQSwECFAAUAAgACAAZSw5D8KU3Ki8AAAAAEAAADgAAAAAAAAAAAAAAAADseQAAdnBzXDAw
MDBcd2IudnhQSwUGAAAAACkAKQCeCgAAV3oAAAAA, className=com.opera.core.systems.OperaProfile}, version=12, opera.launcher=C:\Documents and Settings\user\.launcher\launcher-win32-i86pc.exe, cssSelectorsEnabled=true, proxy={ftpProxy=null, socksPassword=null, sslProxy=null, proxyAutoconfigUrl=null, httpsProxy=null, class=org.openqa.selenium.Proxy, hCode=12226977, httpProxy=null, noProxy=null, socksUsername=null, proxyType=UNSPECIFIED, autodetect=false, socksProxy=null}, opera.product=Opera Desktop, opera.arguments={pd=C:\DOCUME~1\user\LOCALS~1\Temp\opera6653377967761867016profile, debugproxy=127.0.0.1:29119}, opera.no_quit=false, opera.backend=software, opera.port=29119, takesScreenshot=true, opera.no_restart=false}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
    at com.vaadin.testbench.TestBenchElement.click(TestBenchElement.java:135)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.vaadin.testbench.CachedInvocationHandler.invoke(CachedInvocationHandler.java:74)
    at $Proxy12.click(Unknown Source)
    at com.vaadin.tests.push.BasicPush$BasicPushTest.testPush(BasicPush.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at com.vaadin.tests.tb3.TB3Runner$TB3Method.invokeExplosively(TB3Runner.java:158)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at com.vaadin.tests.tb3.TB3Runner$1.evaluate(TB3Runner.java:134)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at com.vaadin.tests.tb3.AllTB3Tests$ParallelScheduler$1.call(AllTB3Tests.java:66)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: No response on ECMAScript evaluation command
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Windows XP', os.arch: 'x86', os.version: '5.1', java.version: '1.6.0_15'
Driver info: driver.version: unknown
Build info: version: '2.33.0', revision: '4ecaf82108b2a6cc6f006aae81961236eba93358', time: '2013-05-22 12:00:17'
System info: os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-17-pve', java.version: '1.6.0_32'
Driver info: driver.version: unknown
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:277)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:235)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:274)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:235)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:274)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:235)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:274)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:235)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:274)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:235)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:274)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.eval(ScopeEcmascriptService.java:235)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.callFunctionOnObject(ScopeEcmascriptService.java:307)
    at com.opera.core.systems.scope.stp.services.ScopeEcmascriptService.callFunctionOnObject(ScopeEcmascriptService.java:300)
    at com.opera.core.systems.OperaWebElement.callMethod(OperaWebElement.java:95)
    at com.opera.core.systems.OperaWebElement.assertElementNotStale(OperaWebElement.java:664)
    at com.opera.core.systems.OperaWebElement.click(OperaWebElement.java:120)
    at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:63)
    at $Proxy2.click(Unknown Source)
    at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:29)
    at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

___
 Imported from https://dev.vaadin.com/ issue #12367

**Comment by Artur-** [comment]
This is something which would need to be fixed in OperaDriver, if somebody is still using Opera 12 these days
