### ISSUE TITLE
ComboBoxElement with Icons -> Timeout

### ISSUE THREAD

**Issue by andrinbetschart** [vaadin/testbench#916]
We are on Vaadin 8.1.0.rc2 using TestBench 5.0.0 on IE. 

Everything worked well with selecting ComboBoxes by using: 
ComboBoxElement leftComboBox = $(ComboBoxElement.class).id("leftComboBox");

But since I added another ComboBox that uses Icons (setItemIconGenerator) nothing works anymore. I cannot select a single ComboBox anymore, it always ends in a timeout. If I remove the Icons everything works fine again.

I get the following Exception:

org.junit.runners.model.TestTimedOutException: test timed out after 120 seconds

 at java.net.SocketInputStream.socketRead0(Native Method)
 at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
 at java.net.SocketInputStream.read(SocketInputStream.java:170)
 at java.net.SocketInputStream.read(SocketInputStream.java:141)
 at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
 at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
 at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
 at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
 at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
 at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
 at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
 at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
 at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
 at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
 at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
 at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
 at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
 at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
 at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
 at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
 at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
 at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
 at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
 at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
 at com.vaadin.testbench.commands.TestBenchCommandExecutor.waitForVaadin(TestBenchCommandExecutor.java:114)
 at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst328_0._d67waitForVaadin(TestBenchDriverProxy_$$_jvst328_0.java)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at com.vaadin.testbench.DriverInvocationHandler.invoke(DriverInvocationHandler.java:56)
 at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst328_0.waitForVaadin(TestBenchDriverProxy_$$_jvst328_0.java)
 at com.vaadin.testbench.TestBenchElement.waitForVaadin(TestBenchElement.java:161)
 at com.vaadin.testbench.TestBenchElement.findElement(TestBenchElement.java:283)
 at com.vaadin.testbench.elements.ComboBoxElement.getInputField(ComboBoxElement.java:217)
 at com.vaadin.testbench.elements.ComboBoxElement.isTextInputAllowed(ComboBoxElement.java:108)
 at com.vaadin.testbench.elements.ComboBoxElement.selectByText(ComboBoxElement.java:51)
 at ch.concordia.fachtest.cockpit.webapp.guitests.pageobjects.PlanungPageObject.selectComboBoxValue(PlanungPageObject.java:25)
 at ch.concordia.fachtest.cockpit.webapp.guitests.pageobjects.PlanungPageObject.selectLeftComboBoxValue(PlanungPageObject.java:16)
 at ch.concordia.fachtest.cockpit.webapp.guitests.PlanningGuiTest.createTestTaskWithDragAndDrop_screenshot_comparison(PlanningGuiTest.groovy:81)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
 at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
 at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
 at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
 at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.lang.Thread.run(Thread.java:745)

**Comment by Petikoch** [comment]
@andrinbetschart there are some commits regarding this issue. 

Do you think this issue is fixed? With which TestBench Version?

Best regards,
Peti

**Comment by Artur-** [comment]
Based on https://github.com/vaadin/framework/pull/9717, this should be fixed in testbench api 8.1.2
